### ISSUE TITLE
Note: the current version in 'master branch does not work, probably  I have some issues with it

### ISSUE THREAD

**Issue by mindfulme** [google/emoji-scavenger-hunt#20]
Basically, from the other branch, everything is okay, I take the source files from 'fix-reshape' everything launches - okay. I suggest review files or readme in the master branch

**Comment by mindfulme** [comment]
git checkout fix-reshape

**Comment by tushuhei** [comment]
Closing this issue assuming this is a duplicated issue of #14. We're working on the upstream issues to make the training script work. Please subscribe #14 to get the latest status on the fix.
