### ISSUE TITLE
How to re-train this model, probably, someone can provide brief instructions. Gracious party saver

### ISSUE THREAD

**Issue by mindfulme** [google/emoji-scavenger-hunt#21]
I do want to try the neural net model for several experiments, I would be proud of you if you managed to help me :P

**Comment by tushuhei** [comment]
Thank you for trying out that! The general instruction for retraining is available at
https://github.com/google/emoji-scavenger-hunt#build-your-own-model
You may need to use `fix-reshape` branch instead of `master` until the issue #14 is solved fully.

Could you elaborate the steps you have tried to build your own model so far? It would be helpful to update README accordingly to make it more easy to follow.

**Comment by RadEdje** [comment]
Hi, i would also like to retrain the model but I was hoping I could get to the actual python files inside the docker image once built. Is there a way to do that? I don't want to use docker. I already have a python environment with tensorflow-gpu running (ver 1.7). I just want to understand how to do a savedModel for image classification/detection and convert it with tensorflow.js (which the emoji-scavenger hunt does),  and run it in my own web app. I'm trying to build a radiology program. Thanks for any suggestions.

**Comment by tushuhei** [comment]
Hi there,
The game is using the retrained model generated by the training script below.
https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/examples/image_retraining/retrain.py
If you don't want to use Docker, you can simply run the script from your python environment and convert the output with [TensorFlow.js converter](https://github.com/tensorflow/tfjs-converter).

**Comment by RadEdje** [comment]
Thanks a lot @tushuhei ! hope I can still ask about the contents of the file. Reading up on the "builder" for the SavedModel right now. Thanks again!

**Comment by RadEdje** [comment]
@tushuhei Hi, i've successfully run the retrain.py in my current python venv. (it seems there are 2 versions of retrain.py. The one you linked to seems to be the newer one that produces the more current SavedModel directory while the old one from tensorflow-for-poets-2 on the tensorflow-hub produces the older and likely deprecated frozen.pb).   

Now to my new problem. I hope you don't mind if I still ask you. I was able to create a SavedModel directory. I then ran tensorflow_converter using python.

This is my directory structure:

```
tensorgpu/
   Scripts/
     tensorflowjs_converter.exe
   poets/
     tensorflow-for-poets-2/
       tf_files/
         saved_models2/
           variables/
             variables.data-000000-of-00001
             variables.index
           saved_model.pb
         conversion/
           webmodel
```



(I kept out the other files for simplicity)

and here is my code using tensorflow_converter

```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --output_node_names='MobilenetV1/Predictions/Reshape_1' \
    --saved_model_tags=serve\
    /poets/tensorflow-for-poets-2/tf_files/saved_models2 \
    /poets/tensorflow-for-poets-2/tf_files/conversion/webmodel
```


When I run this, it says [WinError 5] Access is denied: 'C:Program Files/Git/poets'

I'm running it in my virtual venv python environment but it seems to be trying to create a folder for my output files in drive C. I also noticed that it's no longer using my gpu. The old retrain.py script is using tensorflow_gpu.


Any advice would be much appreciated.

thanks!

**Comment by RadEdje** [comment]
just wanted to update for anyone having similar troubles with the tensorflowjs_converter. I got it to work finally. i just removed the "\' between the input and output directories. Weird since the tensorflowjs converter docs includes that "\" at https://github.com/tensorflow/tfjs-converter. Any way, just wanted to share.

**Comment by RadEdje** [comment]
Hi, trying to reuse the model I created and converted with tensorflowjs_converter. Looked at the redistributable folder of the emoji scavenger hunt. It seems to have a bundle.js? probably produced from the src folder scripts (written in ts? is that type script?) with yarn? i don't really need all the logic of the emoji game. Is there a way to write it all in plain javascript? I just want to run the model using my phone's camera then see or log the output label along with the percentage confidence. From there I can hopefully write my own logic. Any suggestions would be most appreciated. Thanks a lot! update: I'm currently reading this part of the docs: https://github.com/tensorflow/tfjs-converter but the link for the mobilenet demo gives a 404 page. I'm also looking at this link https://js.tensorflow.org/tutorials/webcam-transfer-learning.html.

**Comment by jbruwer** [comment]
Hey!

Yes, bundle.js is our compiled javascript for the game logic. It is generated from the TypeScript files in the src directory. You don't need the logic from the game to make basic camera prediction work. The relevant lines in Javascript you would need is the part that accesses the camera and does prediction, see https://github.com/google/emoji-scavenger-hunt/blob/master/src/js/game.ts#L347

In order to initilize the model and camera you can look at this code snippet https://github.com/google/emoji-scavenger-hunt/blob/master/src/js/game.ts#L406

Hope that helps!

**Comment by RadEdje** [comment]
@jbruwer Thanks! I'll check out those links.

**Comment by RadEdje** [comment]
Hi I'm back with a few questions. I've tried to simplify my code for a simple version to categorize what my mobile phone's camera sees in the browser. 

I've trained a model with python using tensroflow using the retrain.py at this link https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/examples/image_retraining/retrain.py

I've saved a SavedModel directory.

I've converted the SavedModel with tensorflowjs_conerter.

I'm capturing video from the camera and placed it in a video tag.

Now I just want to experiment and read/categorize the realtime video capture of the camera in a video element on my html page and console log the predictions of the model first.


But I seem to be having trouble with async/await. 

Currently studying 

https://github.com/tensorflow/tfjs-converter.

and I'm stumped at this part of the code (loading my python converted saved js model for use in the browser):


```
import * as tf from '@tensorflow/tfjs';
import {loadFrozenModel} from '@tensorflow/tfjs-converter';

/*1st model loader*/
const MODEL_URL = './model/web_model.pb';
const WEIGHTS_URL = '.model/weights_manifest.json';
const model = await loadFrozenModel(MODEL_URL, WEIGHTS_URL);

/*2nd model execution in browser*/
const cat = document.getElementById('cat');
model.execute({input: tf.fromPixels(cat)});
```

I noticed it's using es6 (import/export) and es2017 (async/await) so I've used babel with babel-preset-env, babel-polyfill and babel-plugin-transform-runtime. I've used webpack but switched over to Parcel as my bundler . In both bundlers I keep getting the error that the await should be wrapped in an async function so I wrapped the first part of the code in an async function hoping to get a Promise.

```
async function loadMod(){

const MODEL_URL = './model/web_model.pb';
const WEIGHTS_URL = '.model/weights_manifest.json';
const model = await loadFrozenModel(MODEL_URL, WEIGHTS_URL);

}

loadMod();
```

now both builders say that the 'await is a reserved word'. vscode eslinter says that loadMod(); has a Promise void. (so the promise failed or got rejected?)
I'm trying to reference the javascript model files using a local relative path or is this wrong? I have to 'serve' the ML model from the cloud? It can't be from a relative local path?

Any suggestions would be much appreciated. Thanks!

**Comment by jbruwer** [comment]
I don't have experience using webpack or Parcel but the exact bundler you use shouldn't affect the code. Our code uses plain ES6 style typescript. The relevant camera and model setup code is [here](https://github.com/google/emoji-scavenger-hunt/blob/master/src/js/game.ts#L406). We run that inside a Promise.all to ensure that both the camera and model has been initialized correctly before doing anything. You should be able to use our mobilenet.ts example as a base since that also loads the model files locally, see https://github.com/google/emoji-scavenger-hunt/blob/master/src/js/mobilenet.ts

**Comment by RadEdje** [comment]
Hi, thanks a lot for replying. Really appreciate it @jbruwer .


Here's a link to my github repo for the index.js for the currently non-working project i'm tryng to write. It's a mix-match currently of the various tutorials and files from tensorflow.js examples. Just trying to figure out how to get it to work before I start on my own project idea.

https://github.com/RadEdje/radLense/blob/master/index.js

Btw, I used the retrain.py for the emoji scavenger hunt google experiment to train and build the model using my python env environment (din't use docker but thanks to @tushuhei and your links here, I got the original retrain.py which I plugged into my python tensorflow-gpu environment). The model works in python.

I then converted the model (with the python tensorflow_converter) into the weights.json, model.pb file and the shards and put them in a model folder.

Now with tensorflow.js, 
I used an async function to load the converted model:

async function runMod(){
  const MODEL_URL = "model/tensorflowjs_model.pb";
  const WEIGHTS_URL = "model/weights_manifest.json";

  console.log(MODEL_URL);
  console.log(WEIGHTS_URL);
  console.log('before loadFrozenModel');

  const model = await loadFrozenModel(MODEL_URL,WEIGHTS_URL);

  console.log('after loadFrozenModel');


}

runMod();


I did this just to see if it loads at all.

All the console.logs work except the one after

  const model = await loadFrozenModel(MODEL_URL,WEIGHTS_URL);

so I've narrowed it down to this line. then I get the error;

node_modules\core-js\library\modules\_object-dp.js:9 Unhandled promise rejection TypeError: Cannot read property 'loadWeights' of undefined
    at FrozenModel.<anonymous> (node_modules\@tensorflow\tfjs-layers\dist\callbacks.js:446)
    at step (node_modules\@tensorflow\tfjs-layers\dist\callbacks.js:340)
    at Object.next (node_modules\@tensorflow\tfjs-layers\dist\callbacks.js:321)
    at fulfilled (node_modules\@tensorflow\tfjs-layers\dist\callbacks.js:312)


so could it still be the shards?


Anyway,
I've also been posting on the tensorflow.js forums and there might be an issue with version compatibility with tensorflow_converter and tensorflow-core. Here's the link to that forum just if you're interested.

https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/tfjs/DBJ1RgWeLCo/GZp5_i-WCAAJ

Thanks again for finding time to answer my questions. 
Just want a simple js example to help me load any model with loadFrozenModel and console log the prediction from there. 
Keras' tf.loadModel() doesn't seem to have any of these issues though from what I hear. Cant i just use tf.loadModel? or is that strictly for Keras models.... anyway thanks again.

**Comment by RadEdje** [comment]
Hi, 
just thought I'd ask here again.
I've been asking mainly at the google groups tensorflow forums but now I'm back to the webcam part of the emoji scavenger hunt. 

Just a quick summary of where I'm at... what works and what does not;
I hope someone can help.

I've switched to Keras using TF as a backend.
Converted to tf model.js with shards.
Ditched all bundlers, builders, babel, preprocessors, yarn, webpack, parcel etc. and using raw vanilla js.
Currently shows the probablities of each predicted category for a single static image in a an image element as a single array/tensor.

Now for my question.

1) Currently using code snippets from emoji scavenger hunt app. I'm now switching from single static image to capturing image data directly from the web cam and putting it into a video html tag for prediction. this is the code that I'm using.


async function kerasMod() {

    console.log('run');

  const model = await tf.loadModel('kerasModel/model.json');
  console.log(model);

  let isPredicting = true;

//   THE LOOP FOR LOGGING PREDICTIONS
  while (isPredicting) {
    const predictedClass = tf.tidy(() => {
      const img = webcam.capture();
      const predictions = model.predict(img);
      return predictions.as1D().argMax();
    });

    const classId = (await predictedClass.data())[0];
    console.log('CLASS ID is '+classId);
    await tf.nextFrame();

  }

}

kerasMod();


class Webcam {

  // class Webcam {

  /**
   * @param {HTMLVideoElement} webcamElement A HTMLVideoElement representing the webcam feed.
   */
  constructor(webcamElement) {
      this.webcamElement = webcamElement;
  }

  /**
   * Captures a frame from the webcam and normalizes it between -1 and 1.
   * Returns a batched image (1-element batch) of shape [1, w, h, c].
   */
  capture() {
      return tf.tidy(() => {
          // Reads the image as a Tensor from the webcam <video> element.
          const webcamImage = tf.fromPixels(this.webcamElement);

          // Crop the image so we're using the center square of the rectangular
          // webcam.
          const croppedImage = this.cropImage(webcamImage);

          // Expand the outer most dimension so we have a batch size of 1.
          const batchedImage = croppedImage.expandDims(0);

          // Normalize the image between -1 and 1. The image comes in between 0-255,
          // so we divide by 127 and subtract 1.
          return batchedImage.toFloat().div(tf.scalar(127)).sub(tf.scalar(1));
      });
  }

  /**
   * Crops an image tensor so we get a square image with no white space.
   * @param {Tensor4D} img An input image Tensor to crop.
   */
  cropImage(img) {
      const size = Math.min(img.shape[0], img.shape[1]);
      const centerHeight = img.shape[0] / 2;
      const beginHeight = centerHeight - (size / 2);
      const centerWidth = img.shape[1] / 2;
      const beginWidth = centerWidth - (size / 2);
      return img.slice([beginHeight, beginWidth, 0], [size, size, 3]);
  }

  /**
   * Adjusts the video size so we can make a centered square crop without
   * including whitespace.
   * @param {number} width The real width of the video element.
   * @param {number} height The real height of the video element.
   */
  adjustVideoSize(width, height) {
      const aspectRatio = width / height;
      if (width >= height) {
          this.webcamElement.width = aspectRatio * this.webcamElement.height;
      } else if (width < height) {
          this.webcamElement.height = this.webcamElement.width / aspectRatio;
      }
  }

  async setup() {
      return new Promise((resolve, reject) => {
          const navigatorAny = navigator;
          navigator.getUserMedia = navigator.getUserMedia ||
              navigatorAny.webkitGetUserMedia || navigatorAny.mozGetUserMedia ||
              navigatorAny.msGetUserMedia;
          if (navigator.getUserMedia) {
              navigator.getUserMedia({
                      video: true
                  },
                  stream => {
                      this.webcamElement.srcObject = stream;
                      this.webcamElement.addEventListener('loadeddata', async () => {
                          this.adjustVideoSize(
                              this.webcamElement.videoWidth,
                              this.webcamElement.videoHeight);
                          resolve();
                      }, false);
                  },
                  error => {
                      document.querySelector('#no-webcam').style.display = 'block';
                  });
          } else {
              reject();
          }
      });
  }



}


const webcam = new Webcam(document.getElementById('videoElement'));

console.log(webcam);


So console.log(webcam); works so the constructor for webcam runs smoothly which Means I'm getting the pixel data as a tensor.
However, I'm getting this new error.

Uncaught (in promise) Error: Requested texture size [0x0] is invalid.
    at Object.n.validateTextureSize (tfjs.js:1)
    at s (tfjs.js:1)
    at Object.n.createMatrixTexture (tfjs.js:1)
    at e.createMatrixTexture (tfjs.js:1)
    at e.acquireTexture (tfjs.js:1)
    at e.uploadToGPU (tfjs.js:1)
    at e.getTexture (tfjs.js:1)
    at e.fromPixels (tfjs.js:1)
    at e.fromPixels (tfjs.js:1)
    at e.fromPixels (tfjs.js:1)

so the requested texture size is invalid. Any suggestions? thanks again for any help or suggestions.
Should I change my video element to full screen like what you guys did for the phone app?

Thanks again for any advice and more power to sharing and #democratizingAI

**Comment by RadEdje** [comment]
just to update, I resized my html video element to 244 pixels. It's predicting now on the web, with vanilla raw javascript but it's giving me 0 or 1. I guess that refers to my two categories. How do I get the 2 category names or rather how do I know if 0 refers to cat while 1 refers to dog or vice versa... thanks.

**Comment by tushuhei** [comment]
The correspondences between output indexes and category names are described
in output_labels.txt. Please update src/js/scavenger_classes.ts to reflect
them in frontend.

2018年5月26日(土) 15:53 ERWIN JOHN T. CARPIO, MD, FPCR <notifications@github.com

**Comment by RadEdje** [comment]
thanks @tushuhei ... will do that ASAP.....

**Comment by RadEdje** [comment]
Hi, finally designing my apps own logic.... just a few questions if you have the time..

Currently using 
 
while (isPredicting) {
                        const predictedClass = tf.tidy(() => {
                            const img = webcam.capture();
                            const predictions = model.predict(img);
                            return predictions.as1D().argMax();
                        });
                        // predictedClass.print();
                        const classId = (await predictedClass.data())[0];


so I use .as1D to flatten the tensor into one dimension then get argMax to  get the index with the highest value... but how do I get the percentages of each index or category. Say I want an object in the form {class1: 0.95, class2: 0.65, class3: 0.35} etc  then  I can use that object for my app's logic.

I was looking at getTopK but it seems it's not universal.
Any suggestions? thanks a lot

**Comment by tushuhei** [comment]
I believe you can return predictions.as1D(). It should describe the
percentage of each class.

2018年5月26日(土) 23:10 ERWIN JOHN T. CARPIO, MD, FPCR <notifications@github.com

**Comment by tushuhei** [comment]
Closing this issue since the original problem (model retraining) has been solved. Feel free to reopen if you still have any retraining related problem.
