### ISSUE TITLE
I play the game with my own trained model. But it can't identify objects.

### ISSUE THREAD

**Issue by yea759** [google/emoji-scavenger-hunt#24]
Hi, Emoji Scavenger Hunt is really cool game.

I play the game with my own trained model. But it can't identify objects. It takes a picture of any object and tells me I found the item. 

I didn't have any error, so I think maybe the problem is from the image data.

I prepare 400 images about OK(gesture) for training. 
Should I need to prepare more images or select pure background images?

![](https://i.imgur.com/pjDO3rp.png)

**Comment by tushuhei** [comment]
Hi Bella,

Thank you for playing the game. I believe 400 images is large enough.
Please make sure to update `src/js/scavenger_classes.ts` according to
`output_labels.txt`, which is generated by the retraining program. It
describes the new class names for the retained model.

**Comment by yea759** [comment]
Thank you for your reply. I'm not sure my code is correct or not.
Here is the content of my files:

**output_labels.txt**
```
travelfrog
ok
scissors
```
**scavenger_classes.ts**
```
export const SCAVENGER_CLASSES: {[key: number]: string} = {
    0: 'travelfrog',
    1: 'ok',
    2: 'scissors'
};
```
**game_levels.ts**
```
export interface EmojiItem {
  [index: string]: string;
}

export const EMOJIS_LVL_1: Array<EmojiItem> = [
  {
    'name': 'scissors',
    'emoji': '',
    'path': '/img/emojis/game/scissors.svg'
  },
  {
    'name': 'travelfrog',
    'emoji': '',
    'path': '/img/emojis/game/travelfrog.svg'
  },
  {
    'name': 'ok',
    'emoji': '',
    'path': '/img/emojis/game/ok.svg'
  }
];
```

**Comment by tushuhei** [comment]
The change you made looks good to me. Please let me know if you see any trouble after compiling them. Also, you can see how the image detection is working by passing `?debug=true` parameter as instructed at https://github.com/google/emoji-scavenger-hunt/blob/master/src/js/game.ts#L381

**Comment by yea759** [comment]
Thank you for your help. 
I found the problem is from the logic of game. 
When I modified the function of  `checkEmojiMatch` , the game worked very well.

```
if (this.currentEmoji.name === emojiNameTop1.label && emojiNameTop1.value > 0.8)  {
      this.emojiFound();
};
```

**Comment by tinchoforever** [comment]
Same here.
4 categories, 200/300 each category. Any idea?

![mate](https://user-images.githubusercontent.com/719504/44371391-0ed9f100-a4b5-11e8-8007-9fe1e8787432.gif)

<img width="1408" alt="screen shot 2018-08-20 at 8 08 06 pm" src="https://user-images.githubusercontent.com/719504/44371348-d63a1780-a4b4-11e8-9439-edddb1fc4d45.png">

**Comment by tinchoforever** [comment]
Fixed with the same code fix :-)
