### ISSUE TITLE
Trying to Build your own model but returns an error

### ISSUE THREAD

**Issue by oninross** [google/emoji-scavenger-hunt#26]
Using a windows machine at the moment, I got ready and followed the instructions as followed:

`$ cd training
$ docker build -t model-builder .
$ docker run -v /path/to/data:/data -it model-builder`

However, after hitting enter, the error below shows up.

```
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ERROR:tensorflow:Image directory '/data/images' not found.
Traceback (most recent call last):
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1486, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1138, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by tushuhei** [comment]
Looks like the error is caused because the directory for training images is not found. Please update `/path/to/data` to the path of your training dataset.

**Comment by oninross** [comment]
I have updated the path to `/data/images/`.  Still receiving the same error

**Comment by yea759** [comment]
You should update `/path/to/data` to the path of your computer. For example: `C:\emoji-scavenger-hunt\data`

**Comment by oninross** [comment]
I have moved the entire folder to the root of C drive, the image below is my folder structure, the data has 3 folders with the images in them.

I receive this error:

```
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ERROR:tensorflow:Image directory 'C:Usersninoross.rodriguezDesktopemoji-scavenger-hunttrainingdataimages' not found.
Traceback (most recent call last):
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1486, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1138, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

![screenshot_052418_035649_pm](https://user-images.githubusercontent.com/2233813/40466910-12fc940c-5f6b-11e8-9b7a-9cbd8134f8fa.jpg)

**Comment by yea759** [comment]
Update the path: `C:Usersninoross.rodriguezDesktopemoji-scavenger-hunttrainingdataimages\data`

**Comment by oninross** [comment]
~Unable to find image 'model-builder:latest' locally~
~docker: Error response from daemon: pull access denied for model-builder, repository does not exist or may require 'docker login'.~
~See 'docker run --help'.~

you know the funny thing about that error, its nowhere to be found

**Comment by yea759** [comment]
Is this your command?
`$ cd training $ docker build -t model-builder . $ docker run -v C:Usersninoross.rodriguezDesktopemoji-scavenger-hunttrainingdataimages\data:/data -it model-builder`

**Comment by oninross** [comment]
Nope.  See the code below

```
$ cd training
$ docker build -t model-builder .
$ docker run -v C:/emoji-scavenger-hunt/data:/data -it model-builder
```

**Comment by oninross** [comment]
My bad, I edited the file location in the Docker file.  That was causing the issue

**Comment by shahidgeek** [comment]
https://colab.research.google.com/drive/1hFte7dNUZGVukuR0OY02t0atJgMzn6oc#scrollTo=Bl-yFZqKeezp&forceEdit=true&offline=true&sandboxMode=true


**Step 0** 

Replace retrain.py with downloading file from following link and uploading it to same folder in Google drive.

https://raw.githubusercontent.com/tensorflow/hub/master/examples/image_retraining/retrain.py


**Step 1**

Go to this link : 

https://colab.research.google.com/drive/1hFte7dNUZGVukuR0OY02t0atJgMzn6oc#scrollTo=Bl-yFZqKeezp&forceEdit=true&offline=true&sandboxMode=true

**Step 2**

Go to chapter Two

**Step 3** 

**Worked by adding two lines as given following before the script section : LOL**

**It's a LOL that just added following two lines and it worked before script section and it worked.**

**Two Lines:**


    if not os.path.isdir("../Pokemons-subset"):
  
         print('Error')


**Script Section:**


     %run scripts/retrainn.py   \

       --bottleneck_dir=tf_files/bottlenecks   \

       --how_many_training_steps=4000   \

       --model_dir=tf_files/models/   \

       --summaries_dir=tf_files/training_summaries/mobilenet_0.50_160   \

       --output_graph=tf_files/retrained_graph.pb   \

       --output_labels=tf_files/retrained_labels.txt   \

       --learning_rate=0.01   \

       --architecture=mobilenet_0.50_160   \

       --image_dir=../Pokemons-subset \

       --flip_left_right \

       --random_crop=10 \

       --random_scale=10 \

       --random_brightness=10
