### ISSUE TITLE
Detecting Retrained Data

### ISSUE THREAD

**Issue by JCDavie** [google/emoji-scavenger-hunt#32]
I am just looking for some clarity on ensuring I have the right approach on a retrained model:

Assuming I trained just two categories via transfer learning in the retrain.py:

data
└── images
    ├── cat
    │   ├── cat1.jpg
    │   ├── cat2.jpg
    │   └── ...
    └── dog
        ├── dog1.jpg
        ├── dog2.jpg
        └── ...

Would index 0 be cat and index 1 dog?  I assume the order of my output labels needs to match my scavenger classes.

Do i remove the other not trained classes and only leave two?

`export const SCAVENGER_CLASSES: {[key: number]: string} = {
     0: 'cat',
     1: 'dog'
};`

Side note:  I am a little confused, when trying to test my retrained model and its image classification accuracy manually, before converting it to the tensorflowjs format , I used
https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/examples/label_image/label_image.py

But this script only worked with my tmp/output_graph.pb, not my saved_model.pb, is that correct?

**Comment by tushuhei** [comment]
Hi Jamie,
The order of the labels should match with the order in `output_labels.txt`. If your `output_labels.txt` is like:
```
dog
cat
```
the `scavenger_classes.ts` should be like
```js
export const SCAVENGER_CLASSES: {[key: number]: string} = { 0: 'dog', 1: 'cat' };
```

> But this script only worked with my tmp/output_graph.pb, not my saved_model.pb, is that correct?

Yes, `label_image.py` takes the model in Frozen model format which is specified in `--output_graph` param in [retrain.py](https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/examples/image_retraining/retrain.py) and the default value of that is `/tmp/output_graph.pb`.

**Comment by tushuhei** [comment]
Let me close this issue for now. Please feel free to reopen if you still see the issue.
