### ISSUE TITLE
cannot run it ...

### ISSUE THREAD

**Issue by yanlee26** [google/emoji-scavenger-hunt#39]
`[2] /bin/sh: dev_appserver.py: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by jbruwer** [comment]
Hi, were you able to install the Cloud SDK? Under the development [section](https://github.com/google/emoji-scavenger-hunt#development) we mention the relevant tools you need to have installed in order to run the code.

Cheers

**Comment by novian66** [comment]
I was able install Cloud SDK, but when I run yarn prep I get this error

```
$ mkdirp dist && mkdirp dist/js && touch dist/js/bundle.js
'touch' is not recognized as an internal or external command,
operable program or batch file.
```
