### ISSUE TITLE
Number of Objects Trained

### ISSUE THREAD

**Issue by jonobr1** [google/emoji-scavenger-hunt#40]
Out of curiosity, how many objects have been trained with the model packaged in the `/dist` folder?

**Comment by tushuhei** [comment]
Hi Jono,

The model is trained to recognize around 400 objects. For more detail, please take a look at [this blog article](https://medium.com/tensorflow/a-look-at-how-we-built-the-emoji-scavenger-hunt-using-tensorflow-js-3d760a7ebfe6).

Thanks,
Shuhei

**Comment by jonobr1** [comment]
Cool, thanks for the quick response!
