### ISSUE TITLE
Running docker returns errors regarding Tensorflow

### ISSUE THREAD

**Issue by hxk1633** [google/emoji-scavenger-hunt#44]
I've been having trouble managing my tensorflow installations within the docker container. I installed an earlier version of tensorflow (1.9.0) which I specified in docker file and it made this error go away:

`AttributeError: module ‘tensorflow’ has no attribute ‘app’`

But while building my model, this error came up:

` class UnliftedInitializerVariable(resource_variable_ops.UninitializedVariable):
AttributeError: module 'tensorflow.python.ops.resource_variable_ops' has no attribute 'UninitializedVariable'
`
Do I need to upgrade the code to tensorflow 2.0 or is there a problem with the way I installed tensorflow? Any help would be appreciated.

**Comment by jbruwer** [comment]
@tushuhei Do you mind giving some suggestions here

**Comment by shareefalis** [comment]
@hxk1633 is my machine learning intern and I fixed the dockerfile so he can move forward with ML stuff.

The fix: https://github.com/google/emoji-scavenger-hunt/pull/45

**Comment by tushuhei** [comment]
@shareefalis Thank you for the fix!
